### ISSUE TITLE
Outdated links in projects

### ISSUE THREAD

**Issue by hseg** [haskell-cryptography/haskell-cryptography.github.io#6]
Looking around https://haskell-cryptography.org/projects, multiple links I tried were broken:
- [content/projects/_index.md](https://github.com/haskell-cryptography/haskell-cryptography.github.io/blob/main/content/projects/one-time-password.md#L23) points to `hsopenssl`, which has been renamed to `openssl`
- [content/projects/libsodium.md](https://github.com/haskell-cryptography/haskell-cryptography.github.io/blob/main/content/projects/one-time-password.md#L16) refers to `sel.yml`, which was deleted in https://github.com/haskell-cryptography/libsodium-bindings/commit/b11a72bc20990ba81bf4875c372f719fb2da24fc
- [content/projects/one-time-password.md](https://github.com/haskell-cryptography/haskell-cryptography.github.io/blob/main/content/projects/one-time-password.md#L12) points to a broken ref, the entire `/tree/...` suffix should be dropped
- [content/projects/openssl.md](https://github.com/haskell-cryptography/haskell-cryptography.github.io/blob/main/content/projects/openssl.md#L12) points to a broken ref, the entire `/tree/...` suffix should be dropped

Also, wrong repo but the badges on https://github.com/haskell-cryptography/botan are broken at the moment.

Thanks for your efforts to improve haskell's crypto!

**Comment by Kleidukos** [comment]
Thanks!

**Comment by Kleidukos** [comment]
Fixed by feed46dce20ea95809f968bb20c5641ab538d81d
